const responseAxios = {
  data: {
    content: [
      {
        id: 1,
        code: 'Agarak',
        name: 'Agarak',
        description:
          '\n\nAgarak, Armenia es una ciudad ubicada en el sur de Armenia, cerca de la frontera con Irán. Esta ciudad es conocida por sus hermosos paisajes montañosos, sus antiguas ruinas y su cultura única. La ciudad es un destino popular para los amantes de la naturaleza, los aventureros y los turistas interesados en la historia y la cultura armenia.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: {
          id: 81,
          name: 'Armenia',
          name_en: null,
          country: null,
          countryCode: null,
          code: 'AXM',
          codeMB: null,
          codeHertz: null,
          codeHotelBeds: 'AXM',
          codeTourico: null,
          codeHotelDO: null,
          codeBokun: null,
          codeVacancy: null,
          codeTravelPort: null,
          codeOwnersLink: null,
          codeHotelPro: null,
          codeBookinGee: null,
          codeRateHawk: '475',
          codeViator: '29967',
          codeAmadeus: 'AXM',
          codeRci: null,
          codeGiata: null,
          codeTripAdvisor: null,
          enabled: true,
          typeDestination: 'NONE',
        },
      },
      {
        id: 2,
        code: 'Aghavnadzor',
        name: 'Aghavnadzor',
        description:
          '\n\nAghavnadzor, Armenia es un destino hermoso en el Cáucaso Sur. Está rodeado de montañas impresionantes y ofrece una variedad de actividades al aire libre, como senderismo, ciclismo y esquí. La ciudad también es famosa por sus antiguas iglesias armenias, sus museos y su arquitectura tradicional.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: {
          id: 81,
          name: 'Armenia',
          name_en: null,
          country: null,
          countryCode: null,
          code: 'AXM',
          codeMB: null,
          codeHertz: null,
          codeHotelBeds: 'AXM',
          codeTourico: null,
          codeHotelDO: null,
          codeBokun: null,
          codeVacancy: null,
          codeTravelPort: null,
          codeOwnersLink: null,
          codeHotelPro: null,
          codeBookinGee: null,
          codeRateHawk: '475',
          codeViator: '29967',
          codeAmadeus: 'AXM',
          codeRci: null,
          codeGiata: null,
          codeTripAdvisor: null,
          enabled: true,
          typeDestination: 'NONE',
        },
      },
      {
        id: 3,
        code: 'Aghdzk',
        name: 'Aghdzk',
        description:
          '\n\nAghdzk, Armenia es una ciudad histórica ubicada en el sur de Armenia. Está rodeada de montañas y valles, y es famosa por sus ruinas antiguas, iglesias y monasterios. Esta ciudad es un destino turístico popular para aquellos que buscan explorar la cultura armenia y disfrutar de la belleza natural de la región.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: {
          id: 81,
          name: 'Armenia',
          name_en: null,
          country: null,
          countryCode: null,
          code: 'AXM',
          codeMB: null,
          codeHertz: null,
          codeHotelBeds: 'AXM',
          codeTourico: null,
          codeHotelDO: null,
          codeBokun: null,
          codeVacancy: null,
          codeTravelPort: null,
          codeOwnersLink: null,
          codeHotelPro: null,
          codeBookinGee: null,
          codeRateHawk: '475',
          codeViator: '29967',
          codeAmadeus: 'AXM',
          codeRci: null,
          codeGiata: null,
          codeTripAdvisor: null,
          enabled: true,
          typeDestination: 'NONE',
        },
      },
      {
        id: 4,
        code: 'Agveran',
        name: 'Agveran',
        description:
          '\n\nAgveran, Armenia es un destino turístico hermoso y pintoresco ubicado en el sur de Armenia. Esta área es conocida por sus impresionantes paisajes montañosos, sus antiguas ruinas y sus tradiciones culturales únicas. Agveran ofrece a los visitantes una variedad de actividades al aire libre, como senderismo, ciclismo, cabalgatas y escalada. También hay muchos lugares históricos para explorar, como el Monasterio de Geghard, el Monasterio de Haghartsin y el Monasterio de Khor Virap. Los visitantes también pueden disfrutar de la deliciosa comida armenia, el vino local y la hospitalidad de los habitantes locales.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 5,
        code: 'Alaverdi',
        name: 'Alaverdi',
        description:
          '\n\nAlaverdi, Armenia es una ciudad histórica ubicada en el norte de Armenia. Está rodeada de montañas y bosques, y es famosa por sus iglesias antiguas y monasterios. La ciudad es un destino popular para los turistas que desean explorar la cultura armenia y disfrutar de la belleza natural de la región.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 6,
        code: 'Amasia',
        name: 'Amasia',
        description:
          '\n\nAmasia, Armenia es una ciudad histórica ubicada en el noroeste de Armenia. Esta ciudad antigua se encuentra en la región de Shirak, cerca de la frontera con Turquía. Amasia es famosa por sus monumentos históricos, como la mezquita de Jumay, la iglesia de San Gregorio y el castillo de Amasia. Esta ciudad también es conocida por sus hermosos paisajes, sus vistas panorámicas y sus numerosos parques y jardines.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 7,
        code: 'Aragats',
        name: 'Aragats',
        description:
          '\n\nAragats, Armenia es una destinación hermosa y única. Está ubicada en el noroeste de Armenia, cerca de la frontera con Turquía. Esta región montañosa ofrece una variedad de paisajes, desde los picos nevados de los cuatro picos de Aragats hasta los valles verdes y los lagos cristalinos. La región también es famosa por sus ruinas antiguas, como el templo de Garni y el monasterio de Geghard. Esta área también ofrece una variedad de actividades al aire libre, desde senderismo hasta ciclismo de montaña.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 8,
        code: 'Aragatsotn',
        name: 'Aragatsotn',
        description:
          '\n\nAragatsotn, Armenia es una región histórica y cultural en el noroeste de Armenia. Está rodeada de montañas y valles hermosos, y es famosa por sus ruinas antiguas, iglesias y monasterios. La región es un destino popular para los amantes de la naturaleza, ya que ofrece una variedad de actividades al aire libre, como senderismo, ciclismo y escalada. También hay muchos sitios históricos y culturales para explorar, como el Castillo de Amberd, el Monasterio de Saghmosavank y el Monasterio de Karmravor.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 9,
        code: 'Aramus',
        name: 'Aramus',
        description:
          '\n\nAramus, Armenia es un destino hermoso y exótico. Está situado en el sur de Armenia, cerca de la frontera con Irán. Esta región es conocida por sus paisajes montañosos, sus lagos y sus antiguas ruinas. La cultura local es una mezcla de tradiciones armenias y persas, lo que la hace única. Los visitantes pueden disfrutar de la arquitectura antigua, la comida local y la hospitalidad de los habitantes.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 10,
        code: 'Areni',
        name: 'Areni',
        description:
          '\n\nAreni, Armenia es una pequeña aldea ubicada en el sur de Armenia, cerca de la frontera con Irán. Esta aldea es famosa por sus vinos, su arquitectura tradicional y sus paisajes hermosos. Está rodeada de montañas y valles, y es un lugar ideal para practicar senderismo y disfrutar de la naturaleza. Además, hay muchas ruinas antiguas para explorar, como la iglesia de Areni, que data del siglo IX. Esta aldea es un destino ideal para aquellos que buscan una experiencia única y auténtica.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 11,
        code: 'Argavand',
        name: 'Argavand',
        description:
          '\n\nArgavand, Armenia es una ciudad histórica ubicada en el sur de Armenia. Está rodeada de montañas y valles, y es famosa por sus ruinas antiguas, iglesias y monasterios. La ciudad es un destino popular para los turistas que desean explorar la cultura armenia y disfrutar de la belleza natural de la región.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 12,
        code: 'Arinj',
        name: 'Arinj',
        description:
          '\n\nArinj, Armenia es una ciudad histórica ubicada en el sur de Armenia. Está rodeada de montañas y valles, y es famosa por sus ruinas antiguas, su arquitectura y sus paisajes naturales. La ciudad es un destino turístico popular debido a sus numerosos monumentos históricos, como la iglesia de San Juan, el monasterio de San Gevorg y el castillo de Arinj. También hay muchas actividades para disfrutar, como senderismo, ciclismo, rafting y pesca.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 13,
        code: 'Armavir',
        name: 'Armavir',
        description:
          '\n\nArmavir, Armenia es una ciudad ubicada en el sur de Armenia, cerca de la frontera con Turquía. Esta ciudad es conocida por sus ruinas antiguas, que datan del siglo IV a. C. y que se encuentran en el sitio arqueológico de Erebuni. Armavir también es famosa por sus numerosos monumentos históricos, como la iglesia de San Juan Bautista, el monasterio de Surb Karapet y el museo de la ciudad. Esta ciudad también ofrece una variedad de actividades al aire libre, como senderismo, ciclismo y rafting.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 14,
        code: 'Armenia',
        name: 'Armenia',
        description:
          '\n\nArmenia es un país situado en el Cáucaso meridional, en el extremo sur de Europa y el extremo noroeste de Asia. Está rodeado por Georgia al norte, Azerbaiyán al este, Irán al sur y Turquía al oeste. Armenia es un país de montañas, con una rica historia y cultura, y una variedad de paisajes naturales. La capital de Armenia es Ereván.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: {
          id: 11839,
          name: 'Armenia',
          name_en: 'Armenia',
          country: 'AM',
          countryCode: 'AM',
          code: 'Armenia',
          codeMB: null,
          codeHertz: null,
          codeHotelBeds: null,
          codeTourico: null,
          codeHotelDO: null,
          codeBokun: null,
          codeVacancy: null,
          codeTravelPort: null,
          codeOwnersLink: null,
          codeHotelPro: null,
          codeBookinGee: null,
          codeRateHawk: '1178',
          codeViator: null,
          codeAmadeus: null,
          codeRci: null,
          codeGiata: '868',
          codeTripAdvisor: '293931',
          enabled: true,
          typeDestination: 'NONE',
        },
      },
      {
        id: 15,
        code: 'Artabuynk',
        name: 'Artabuynk',
        description:
          '\n\nArtabuynk, Armenia es un destino turístico hermoso y único. Está ubicado en el sur de Armenia, cerca de la frontera con Irán. Esta región es conocida por sus impresionantes paisajes montañosos, sus antiguas ruinas y su cultura única. Los visitantes pueden disfrutar de una variedad de actividades, desde senderismo y ciclismo hasta visitas a museos y monumentos históricos. Artabuynk es un destino ideal para aquellos que buscan una experiencia auténtica y única.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 16,
        code: 'Artashat',
        name: 'Artashat',
        description:
          '\n\nArtashat, Armenia es una ciudad histórica ubicada en el sur de Armenia, a orillas del río Aras. Esta ciudad fue la capital del antiguo reino armenio de Artaxias I y fue un importante centro comercial y cultural durante la época de los Artaxiad. Hoy en día, Artashat es una ciudad moderna con una rica historia y cultura, y es un destino turístico popular para los visitantes que desean explorar la historia y la cultura armenias.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 17,
        code: 'Artavan',
        name: 'Artavan',
        description:
          '\n\nArtavan, Armenia es un destino hermoso y pintoresco ubicado en el sur de Armenia. Esta pequeña aldea se encuentra en una zona montañosa y ofrece una vista impresionante de los valles y los picos de las montañas circundantes. La aldea está rodeada de bosques y prados verdes, lo que la hace un lugar ideal para caminar, hacer senderismo y disfrutar de la naturaleza. Los visitantes también pueden disfrutar de la cultura local, con sus tradiciones y costumbres únicas.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 18,
        code: 'Artavaz',
        name: 'Artavaz',
        description:
          '\n\nArtavaz, Armenia es una ciudad histórica ubicada en el noroeste de Armenia. Esta ciudad es famosa por sus iglesias antiguas, monasterios y ruinas de castillos. Esta ciudad también es conocida por sus hermosos paisajes, montañas y valles. Es un lugar ideal para aquellos que buscan una experiencia única y relajante.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 19,
        code: 'Arzakan',
        name: 'Arzakan',
        description:
          '\n\nArzakan, Armenia es una ciudad histórica ubicada en el sur de Armenia. Esta ciudad es famosa por sus ruinas antiguas, sus iglesias antiguas y sus paisajes montañosos. Es un destino ideal para aquellos que buscan una experiencia única y auténtica.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 20,
        code: 'Arzni',
        name: 'Arzni',
        description:
          '\n\nArzni, Armenia es una pequeña ciudad ubicada en el noroeste de Armenia, cerca de la frontera con Georgia. Está rodeada de montañas y bosques, y es famosa por sus fuentes termales y sus vistas panorámicas. La ciudad es un destino popular para los turistas que buscan relajarse y disfrutar de la naturaleza.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 21,
        code: 'Ashotavan',
        name: 'Ashotavan',
        description:
          '\n\nAshotavan, Armenia es un destino único en el Cáucaso. Está situado en la provincia de Aragatsotn, en el noroeste de Armenia. Esta pequeña aldea es famosa por sus antiguas ruinas, que datan del siglo IV a. C. y que se encuentran en la cima de una montaña. Estas ruinas incluyen una iglesia, una fortaleza y una antigua ciudad. La aldea también es conocida por sus hermosos paisajes, que incluyen valles, montañas y lagos. Es un destino ideal para aquellos que buscan una experiencia única y relajante.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: {
          id: 81,
          name: 'Armenia',
          name_en: null,
          country: null,
          countryCode: null,
          code: 'AXM',
          codeMB: null,
          codeHertz: null,
          codeHotelBeds: 'AXM',
          codeTourico: null,
          codeHotelDO: null,
          codeBokun: null,
          codeVacancy: null,
          codeTravelPort: null,
          codeOwnersLink: null,
          codeHotelPro: null,
          codeBookinGee: null,
          codeRateHawk: '475',
          codeViator: '29967',
          codeAmadeus: 'AXM',
          codeRci: null,
          codeGiata: null,
          codeTripAdvisor: null,
          enabled: true,
          typeDestination: 'NONE',
        },
      },
      {
        id: 22,
        code: 'Ashtarak',
        name: 'Ashtarak',
        description:
          '\n\nAshtarak, Armenia es una ciudad histórica ubicada en el norte de Armenia, a unos 20 km al norte de la capital, Ereván. Esta ciudad fue fundada en el siglo VII y es famosa por sus iglesias antiguas, sus ruinas de fortalezas y sus vistas panorámicas de la región. Ashtarak es un destino turístico popular para los visitantes que desean explorar la cultura armenia y disfrutar de la belleza natural de la región.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 23,
        code: 'Aygavan',
        name: 'Aygavan',
        description:
          '\n\nAygavan, Armenia es una ciudad costera ubicada en el sur de Armenia, cerca de la frontera con Irán. Esta ciudad es conocida por sus hermosas playas, sus montañas y sus vistas al mar Caspio. Aygavan también es famosa por sus antiguas ruinas, sus templos y sus iglesias. La ciudad es un destino turístico popular para los amantes de la naturaleza, la historia y la cultura.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 24,
        code: 'Aznvadzor',
        name: 'Aznvadzor',
        description:
          '\n\nAznvadzor, Armenia es una ciudad histórica ubicada en el sur de Armenia. Está rodeada de montañas y valles, y es famosa por sus monumentos antiguos, iglesias y monasterios. La ciudad es un destino turístico popular debido a sus paisajes hermosos y su rica historia.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 25,
        code: 'Bagratashen',
        name: 'Bagratashen',
        description:
          '\n\nBagratashen, Armenia es una ciudad ubicada en el noroeste de Armenia, cerca de la frontera con Georgia. Esta ciudad es conocida por su hermosa arquitectura, su cultura vibrante y sus paisajes impresionantes. Es un destino ideal para aquellos que buscan una experiencia única y auténtica.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 26,
        code: 'Berkaber',
        name: 'Berkaber',
        description:
          '\n\nBerkaber, Armenia es una pequeña aldea situada en el noroeste de Armenia, cerca de la frontera con Turquía. Esta aldea es famosa por sus hermosos paisajes montañosos, sus antiguas iglesias y su cultura única. La aldea es un destino popular para los turistas que buscan disfrutar de la naturaleza y la cultura armenia.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 27,
        code: 'Byurakan',
        name: 'Byurakan',
        description:
          '\n\nByurakan, Armenia es una pequeña aldea ubicada en la provincia de Aragatsotn, Armenia. Está situada en una zona montañosa a unos 1.400 metros sobre el nivel del mar, rodeada de bosques y prados. Esta aldea es famosa por sus observatorios astronómicos, que se remontan al siglo XIX. Esta aldea también es conocida por sus hermosas vistas de la cordillera del Ararat y el Monte Aragats.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 28,
        code: 'Chambarak',
        name: 'Chambarak',
        description:
          '\n\nChambarak, Armenia es una ciudad pequeña y pintoresca ubicada en el noroeste de Armenia. Está rodeada de montañas y bosques, lo que la hace un lugar ideal para la exploración y la aventura. La ciudad es conocida por sus numerosos monumentos históricos, como la iglesia de San Juan, el monasterio de San Gevorg y el monasterio de San Hovhannes. También hay una gran cantidad de parques y jardines, así como una variedad de restaurantes y cafeterías. Chambarak es un destino ideal para aquellos que buscan una experiencia única y relajante.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 29,
        code: 'Chiva',
        name: 'Chiva',
        description:
          '\n\nChiva, Armenia es una ciudad histórica ubicada en el noroeste de Armenia. Esta ciudad es famosa por sus ruinas antiguas, que datan del siglo IX, y por sus iglesias medievales. La ciudad también es conocida por sus paisajes montañosos y sus vistas panorámicas. Chiva es un destino ideal para aquellos que buscan una experiencia única y auténtica de la cultura armenia.',
        typeDestination: 'CITY',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: {
          id: 20261,
          name: 'Chiva',
          name_en: 'Chiva',
          country: 'ES',
          countryCode: 'ES',
          code: 'Chiva',
          codeMB: null,
          codeHertz: null,
          codeHotelBeds: null,
          codeTourico: null,
          codeHotelDO: null,
          codeBokun: null,
          codeVacancy: null,
          codeTravelPort: null,
          codeOwnersLink: null,
          codeHotelPro: null,
          codeBookinGee: null,
          codeRateHawk: '6034633',
          codeViator: null,
          codeAmadeus: null,
          codeRci: null,
          codeGiata: '19813',
          codeTripAdvisor: '1063729',
          enabled: true,
          typeDestination: 'CITY',
        },
      },
      {
        id: 30,
        code: 'Chkalovka',
        name: 'Chkalovka',
        description:
          '\n\nChkalovka, Armenia es una pequeña aldea ubicada en el distrito de Ararat, Armenia. Esta aldea es conocida por sus hermosos paisajes, sus vistas panorámicas y sus antiguas iglesias. Esta aldea es un lugar ideal para aquellos que buscan una escapada tranquila y relajante. La aldea también ofrece una variedad de actividades al aire libre, como senderismo, ciclismo y pesca. Esta aldea es un lugar perfecto para aquellos que buscan una experiencia única y auténtica.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 31,
        code: 'Dashtakar',
        name: 'Dashtakar',
        description:
          '\n\nDashtakar, Armenia es una ciudad histórica ubicada en el sur de Armenia. Esta ciudad es famosa por sus monumentos antiguos, como la iglesia de San Juan, el monasterio de San Juan y el monasterio de San Gevorg. También hay una gran cantidad de museos, parques y jardines para disfrutar. La ciudad es un destino ideal para aquellos que buscan una experiencia cultural única.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 32,
        code: 'Debed',
        name: 'Debed',
        description:
          '\n\nDebed, Armenia es una ciudad histórica ubicada en el norte de Armenia. Está rodeada de montañas y bosques, y es famosa por sus iglesias antiguas y monasterios. La ciudad es un destino popular para los turistas que buscan disfrutar de la naturaleza y la cultura armenia.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 33,
        code: 'Dilijan',
        name: 'Dilijan',
        description:
          '\n\nDilijan, Armenia es una ciudad hermosa ubicada en el corazón de los montes de Armenia. Esta ciudad es conocida por sus hermosos paisajes, sus bosques y sus lagos. Está rodeada de montañas y valles, lo que la hace un lugar ideal para practicar senderismo, ciclismo y otros deportes al aire libre. La ciudad también es famosa por sus antiguas iglesias, monasterios y museos. Esta ciudad es un destino ideal para aquellos que buscan una experiencia única y relajante.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 34,
        code: 'Dsegh',
        name: 'Dsegh',
        description:
          '\n\nDsegh, Armenia es una pequeña aldea ubicada en el distrito de Lori, Armenia. Esta aldea es conocida por sus hermosos paisajes, su cultura única y sus tradiciones antiguas. Está rodeada de montañas y bosques, lo que la hace un lugar ideal para la exploración y la relajación. La aldea también es famosa por sus iglesias antiguas, sus monumentos históricos y sus deliciosos platos tradicionales. Es un destino ideal para aquellos que buscan una experiencia auténtica y una conexión con la cultura armenia.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 35,
        code: 'Dzoraget',
        name: 'Dzoraget',
        description:
          '\n\nDzoraget, Armenia es una pequeña aldea ubicada en el noroeste de Armenia, cerca de la frontera con Georgia. Esta aldea es famosa por sus hermosos paisajes montañosos, sus antiguas iglesias y sus tradiciones locales. Es un lugar ideal para aquellos que buscan una experiencia de viaje única y auténtica.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 36,
        code: 'Dzoraghbyur',
        name: 'Dzoraghbyur',
        description:
          '\n\nDzoraghbyur, Armenia es un destino hermoso con una increíble vista de la naturaleza. Está rodeado de montañas y lagos, y ofrece una variedad de actividades al aire libre, como senderismo, ciclismo y rafting. También hay muchos sitios históricos para explorar, como iglesias antiguas, ruinas y fortalezas. Esta área es un lugar ideal para relajarse y disfrutar de la belleza de Armenia.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 37,
        code: 'Gagarin',
        name: 'Gagarin',
        description:
          '\n\nGagarin, Armenia es una pequeña ciudad situada en el sur de Armenia, cerca de la frontera con Irán. Esta ciudad es conocida por sus hermosos paisajes montañosos, sus antiguas iglesias ortodoxas y su cultura única. La ciudad es un destino popular para los turistas que buscan disfrutar de la naturaleza y la cultura local.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 38,
        code: 'Gandzakar',
        name: 'Gandzakar',
        description:
          '\n\nGandzakar, Armenia es una ciudad histórica ubicada en el noroeste de Armenia, cerca de la frontera con Georgia. Esta ciudad es famosa por sus ruinas antiguas, su arquitectura medieval y sus paisajes montañosos. Es un destino turístico popular para aquellos que buscan explorar la cultura armenia y disfrutar de la naturaleza.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 39,
        code: 'Garni',
        name: 'Garni',
        description:
          '\n\nGarni, Armenia es una ciudad histórica ubicada en el sur de Armenia, cerca de la frontera con Georgia. Esta ciudad es famosa por sus ruinas del templo pagano de Garni, construido en el siglo I d.C. El templo es uno de los únicos restos de la antigua cultura armenia pre-cristiana. La ciudad también alberga una fortaleza medieval, una iglesia armenia y un museo de historia. Garni es un destino turístico popular debido a su ubicación en un hermoso valle rodeado de montañas.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 40,
        code: 'Gavar',
        name: 'Gavar',
        description:
          '\n\nGavar, Armenia es una ciudad ubicada en el noroeste de Armenia, cerca de la frontera con Georgia. Esta ciudad es conocida por sus hermosos paisajes, su arquitectura antigua y sus numerosos monumentos históricos. La ciudad también es famosa por sus deliciosos platos tradicionales y su vibrante cultura. Gavar es un destino ideal para aquellos que buscan una experiencia única y auténtica.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 41,
        code: 'Geghadir',
        name: 'Geghadir',
        description:
          '\n\nGeghadir, Armenia es una ciudad histórica ubicada en el sur de Armenia. Esta ciudad es famosa por sus ruinas antiguas, que datan del siglo IV a. C. Esta ciudad también es conocida por sus iglesias antiguas, que se remontan a los primeros días de la cristiandad. Geghadir también es famosa por sus vistas panorámicas de la región circundante, que incluyen montañas, valles y lagos. Esta ciudad es un destino ideal para aquellos que buscan una experiencia única de la cultura armenia.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 42,
        code: 'Gndevaz',
        name: 'Gndevaz',
        description:
          '\n\nGndevaz, Armenia es una pequeña aldea ubicada en el distrito de Vayots Dzor en Armenia. Esta aldea es famosa por sus vistas panorámicas de la cordillera de Vayk y el río Arpa. Esta aldea también es conocida por sus antiguas iglesias armenias, sus viejas casas de piedra y sus hermosos paisajes. Es un lugar ideal para aquellos que buscan una experiencia de aventura y tranquilidad.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 43,
        code: 'Goght',
        name: 'Goght',
        description:
          '\n\nGoght, Armenia es un destino hermoso y pintoresco ubicado en el sur de Armenia. Esta pequeña aldea se encuentra en un valle rodeado de montañas y ofrece una vista impresionante de la naturaleza. Goght es conocido por sus iglesias antiguas, sus ruinas históricas y sus paisajes de montaña. Esta aldea también es famosa por sus deliciosos vinos y su cocina tradicional. Goght es un destino ideal para aquellos que buscan una experiencia única y relajante.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 44,
        code: 'Gomk',
        name: 'Gomk',
        description:
          '\n\nGomk, Armenia es una ciudad histórica ubicada en el sur de Armenia. Está rodeada de montañas y valles, y es famosa por sus ruinas antiguas, iglesias y monasterios. La ciudad es un destino popular para los turistas que buscan disfrutar de la cultura armenia y la belleza natural de la región.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 45,
        code: 'Goris',
        name: 'Goris',
        description:
          '\n\nGoris, Armenia es una ciudad histórica ubicada en el sur de Armenia, cerca de la frontera con Azerbaiyán. Esta ciudad es conocida por sus impresionantes paisajes montañosos, sus antiguas iglesias y sus numerosos sitios arqueológicos. La ciudad también es famosa por sus numerosos museos, galerías de arte y monumentos históricos. Esta ciudad es un destino ideal para aquellos que buscan una experiencia única y auténtica de la cultura armenia.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 46,
        code: 'Gyulagarak',
        name: 'Gyulagarak',
        description:
          '\n\nGyulagarak, Armenia es una ciudad histórica ubicada en el sur de Armenia. Está rodeada de montañas y valles, y es famosa por sus ruinas antiguas, su arquitectura y sus paisajes naturales. La ciudad es un destino popular para los turistas que buscan disfrutar de la cultura armenia y explorar sus increíbles paisajes.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 47,
        code: 'Gyumri',
        name: 'Gyumri',
        description:
          '\n\nGyumri, Armenia es una ciudad histórica ubicada en el noroeste de Armenia. Esta ciudad es conocida por su arquitectura tradicional, su cultura vibrante y sus paisajes hermosos. Gyumri es un destino ideal para aquellos que buscan una experiencia única y auténtica. Esta ciudad ofrece una variedad de actividades, desde visitar museos y galerías hasta disfrutar de la comida local y la cultura armenia.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 48,
        code: 'Haghpat',
        name: 'Haghpat',
        description:
          '\n\nHaghpat, Armenia es una pequeña aldea ubicada en el norte de Armenia, cerca de la frontera con Georgia. Esta aldea es famosa por sus monasterios medievales, que datan del siglo X y están rodeados de hermosos paisajes montañosos. Los visitantes pueden disfrutar de la arquitectura única de los monasterios, así como de la tranquilidad y la belleza de la naturaleza.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 49,
        code: 'Halidzor',
        name: 'Halidzor',
        description:
          '\n\nHalidzor, Armenia es una pequeña aldea ubicada en el sur de Armenia, cerca de la frontera con Irán. Esta aldea es famosa por sus impresionantes vistas de la montaña y sus antiguas iglesias armenias. Esta aldea es un lugar ideal para aquellos que buscan una experiencia de aventura y tranquilidad.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
      {
        id: 50,
        code: 'Hankavan',
        name: 'Hankavan',
        description:
          '\n\nHankavan, Armenia es una pequeña ciudad situada en el norte de Armenia, cerca de la frontera con Georgia. Está rodeada de montañas y bosques, y es famosa por sus lagos y ríos. La ciudad es conocida por sus paisajes hermosos, sus antiguas iglesias y sus tradiciones culturales. Es un destino ideal para aquellos que buscan una experiencia única y relajante.',
        typeDestination: 'NONE',
        state: {
          id: 1,
          name: 'Armenia',
          code: 'Armenia',
          country: { id: 1, code: 'AM', name: 'Armenia' },
        },
        modelParseDestination: null,
      },
    ],
    pageable: {
      sort: { sorted: false, unsorted: true, empty: true },
      pageNumber: 0,
      pageSize: 50,
      offset: 0,
      paged: true,
      unpaged: false,
    },
    last: false,
    totalPages: 1857,
    totalElements: 92802,
    first: true,
    sort: { sorted: false, unsorted: true, empty: true },
    number: 0,
    numberOfElements: 50,
    size: 50,
    empty: false,
  },
  status: 200,
  statusText: '',
  headers: {
    'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
    'content-type': 'application/json',
    expires: '0',
    pragma: 'no-cache',
  },
  config: {
    transitional: { silentJSONParsing: true, forcedJSONParsing: true, clarifyTimeoutError: false },
    adapter: ['xhr', 'http'],
    transformRequest: [],
    transformResponse: [],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: {},
    headers: {
      Accept: 'application/json, text/plain, */*',
      Authorization:
        'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODM2ODA1NDQsImlzcyI6Imh0dHA6Ly9hcGkuc3Vuc2V0LmNvbS5teDo4MDgwIiwiYXVkIjoic2VjdXJlLWFwcCIsInN1YiI6ImJvdW5fdmlhamUiLCJleHAiOjE2ODM3MDkzNDQsInJvbCI6WyJST0xFX0FQSSJdfQ.FzqzVlcx1MPtx0EoIdSf6MkbDVJnAe0S-V-w_ooEVo6-eYZSzJQd_DjbUAIgtgp0ctFUpn3STg6Jsp4logffnw',
    },
    baseURL: 'http://104.131.92.59:8080/sun-api/v2',
    method: 'get',
    url: '/destination?page=1',
  },
  request: {},
};
export default responseAxios;
